/* eslint-disable */
// Seed script for Aadyaa Jewels — run with: node prisma/seed.js
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const px = (id) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940`;

const categories = [
  {
    name: "Rings",
    slug: "rings",
    description: "Classic to contemporary diamond rings for every moment.",
    image: '/rings/versailles-hidden-halo-diamond-ring-2.webp',
    sortOrder: 1,
  },
  {
    name: "Solitaires",
    slug: "solitaires",
    description: "Timeless single-stone brilliance, engineered to perfection.",
    image: '/rings/atelier-solitaire-ring-2.jpg',
    sortOrder: 2,
  },
  {
    name: "Pendants",
    slug: "pendants",
    description: "Graceful pendants that catch the light with every move.",
    image: '/necklaces/malibu-blue-lab-diamond-solitaire-pendant-3.jpg',
    sortOrder: 3,
  },
  {
    name: "Earrings",
    slug: "earrings",
    description: "Studs, drops and hoops — quiet luxury for every day.",
    image: '/earrings/brigitte-pink-tourmaline-and-rose-quartz-drop-earrings.jpg', 
    sortOrder: 4, 
  },
  {
    name: "Necklaces & Mangalsutras",
    slug: "necklaces-mangalsutras",
    description: "Statement necklaces and mangalsutras crafted for celebrations.",
    image: '/necklaces/dita-lab-grown-diamond-necklace.jpg',
    sortOrder: 5,
  },
  {
    name: "Bangles & Bracelets",
    slug: "bangles-bracelets",
    description: "Wrist adornments in gold, crafted to be treasured.",
    image: '/bangles/certified-lab-diamond-classic-tennis-bracelet.webp',
    sortOrder: 6,
  },
];

const products = [
  {
    name: "Versailles  Hidden Halo  Diamond Ring",
    slug: "versailles-hidden-halo-diamond-ring",
    tagline: "Delicate solitaire with a hidden halo",
    description:
      "The Versailles Hidden Halo Diamond Ring pairs a brilliant round lab-grown diamond with a slender 14K gold band and a hidden halo that amplifies its fire. Ethically grown, CVD-certified and finished by master artisans in New Delhi.",
    price: 66024,
    compareAtPrice: 72000, 
    metal: "14K Yellow Gold",
    carat: 0.5, 
    clarity: "VS1",
    images: ['/rings/versailles-hidden-halo-diamond-ring.webp', '/rings/versailles-hidden-halo-diamond-ring-2.webp'], 
    category: "rings",  
    isNew: true,
    rating: 4.9,
    reviews: 42,
  },
  {
    name: "Camellia Hidden Accent 1.5mm Diamond Ring",
    slug: "camellia-hidden-accent-1.5mm-diamond-ring",
    tagline: "Yellow & Rose gold romance",
    description:
      "The Camellia ring wraps a brilliant diamond in warm rose gold with a twisted shank design. A bestseller for good reason — effortless, feminine and luminous.",
    price: 83350,
    metal: "14K Yellow Gold",
    carat: 0.9,
    clarity: "VS1",
    images: ['/rings/camellia-hidden-accent-1.5mm-diamond-ring.webp', '/rings/camellia-hidden-accent-1.5mm-diamond-ring-2.webp'],
    category: "rings", 
    isBestseller: true,
    rating: 4.8,
    reviews: 56,
  },
  {
    name: "Demi Three-Quarter Diamond Ring",
    slug: "demi-three-quarter-diamond-ring",
    tagline: "Everyday elegance, sustainably grown",
    description:
      "A petite 0.4 carat lab-grown diamond in a comfortable low-profile setting — the everyday ring that goes from desk to dinner without missing a beat.",
    price: 60751,   
    metal: "14K White Gold",
    carat: 0.4,
    clarity: "VS2",
    images: ['/rings/demi-three-quarter.webp', '/rings/demi-three-quarter-coverage-diamond-ring.avif'],
    category: "rings", 
    isNew: true,
    rating: 4.7, 
    reviews: 19,
  },
  {
    name: "Freesia Ring With Sia Diamond Open Ring",
    slug: "freesia-ring-with-sia-diamond-open-ring",
    tagline: "Bold, masculine, brilliant",
    description:
      "A sculpted yellow gold band with a single channel-set lab-grown diamond. Crafted for the modern man who appreciates quiet power.",
    price: 82321,
    metal: "14K Yellow Gold",
    carat: 1.0, 
    clarity: "VS1",
    images: ['/rings/freesia-ring-with-sia-diamond-open-ring.png', '/rings/freesia-ring-with-sia-diamond-open-ring-2.png'],  
    category: "rings",
    isBestseller: true,  
    rating: 4.8,
    reviews: 23,
  },
  {
    name: "East West Atelier Diamond Ring",
    slug: "east-west-atelier-diamond-ring",
    tagline: "Maximum brilliance, zero compromise",
    description:
      "A 1.5 carat centre stone encircled by a pavé halo, set in 18K gold. The Aadya atelier ring delivers engagement-level sparkle with fully ethical provenance.",
    price: 112400,
    compareAtPrice: 124500,
    metal: "18K Yellow Gold",
    carat: 1.5,
    clarity: "VVS2",
    images: ['/rings/east-west-atelier-diamond-ring-2.webp', '/rings/east-west-atelier-diamond-ring.webp'],
    category: "rings",
    isNew: true,
    rating: 4.9,
    reviews: 31,
  },
  {
    name: "Half Moon Three Stone Bezel Diamond Ring",
    slug: "half-moon-three-stone-bezel-diamond-ring",
    tagline: "A ring that sparkles with brilliance",
    description:
      "A stunning half-moon three stone  ring adorned with brilliant diamonds, perfect for adding a touch of elegance to any ensemble.",
    price: 122400,
    compareAtPrice: 124500,
    metal: "14K Yellow Gold",
    carat: 1.5,
    clarity: "VVS2",
    images: ['/rings/half-moon-three-stone-bezel-diamond-ring.png', '/rings/half-moon-three-stone-bezel-diamond-ring-2.jpg'],
    category: "rings",
    isNew: true,
    rating: 4.9,
    reviews: 31, 
  },
  {
    name: "Luxe Rhiannon Three Stone Diamond Engagement Ring",
    slug: "luxe-rhiannon-three-stone-diamond-engagement-ring",
    tagline: "A symbol of love and commitment",
    description:
      "A beautiful diamond engagement ring that symbolizes love and commitment.",
    price: 132400,
    compareAtPrice: 134500,
    metal: "18K White Gold",
    carat: 1.5,
    clarity: "VVS2",
    images: [
      '/rings/luxe-rhiannon-three-stone-sapphire-ring.png',
      '/rings/luxe-rhiannon-three-stone-diamond-ring.png',
    ],
    category: "rings",
    isNew: true,
    rating: 4.5,
    reviews: 36,
  },
  {
    name: "Engagement  Diamond Ring",
    slug: "engagement-diamond-ring",
    tagline: "A ring that sparkles with brilliance",
    description:
      "A luxe rhiannon three stone diamond engagement ring that captures the light and attention of everyone around you.",
    price: 152400,
    compareAtPrice: 154500,
    metal: "18K White Gold",
    carat: 1.5,
    clarity: "VVS2",
    images: [
      '/rings/luxe-rhiannon-three-stone-diamond-ring.png', 
      '/rings/luxe-rhiannon-three-stone-diamond-ring-2.webp'],
    category: "rings",
    rating: 4.4, 
    reviews: 39,
  },
  {
    name: "Engagement, Luxe Nadia Diamond Ring in 18K Yellow Gold",
    slug: "luxe-nadia-diamond-ring-in-18k-yellow-gold",
    tagline: "A ring that exudes elegance and sophistication", 
    description:
      " A stunning 18K yellow gold ring adorned with brilliant diamonds, perfect for adding a touch of elegance to any ensemble.",
    price: 162400,
    compareAtPrice: 164500,
    metal: "18K Yellow Gold",
    carat: 1.5,
    clarity: "VVS2",
    images: ['/rings/luxe-nadia-diamond-ring in-18k-yellow-gold.webp'],
    category: "rings",
    isNew: true,
    rating: 4.4,
    reviews: 39,
  },
  {
    name: "Arden  Diamond Ring With Lab Emerald Accents",
    slug: "arden-diamond-ring-with-lab-emerald-accents",
    tagline: "A modern classic in platinum",
    description:
      "A refined cathedral setting in platinum, holding a 1.2 carat lab-grown diamond of VVS1 clarity. Arden is designed for the moment you say yes — and every day after.",
    price: 100742,
    compareAtPrice: 118000, 
    metal: "14K Yellow Gold",
    carat: 1.2, 
    clarity: "VVS1",
    images: ['/rings/arden-diamond-ring-with-lab-emerald-accents.png', '/rings/arden-diamond-ring-with-lab-emerald-accents-2.webp'],
    category: "rings",
    isBestseller: true, 
    rating: 5.0,
    reviews: 28,
  },
  {
    name: "Luxe Secret Garden Diamond Ring For Engagement",
    slug: "luxe-secret-garden-diamond-ring",
    tagline: "A luxe secret garden diamond ring that exudes elegance.", 
    description:
      " A stunning 18K yellow gold ring adorned with brilliant diamonds, perfect for adding a touch of elegance to any ensemble.",
    price: 162400,
    compareAtPrice: 164500,
    metal: "18K White Gold",
    carat: 1.5,
    clarity: "VVS2",
    images: [
      '/rings/luxe-secret-garden-diamond-ring.webp',
      '/rings/luxe-secret-garden-diamond-ring-2.webp',
      '/rings/luxe-secret-garden-diamond-ring-3.webp'
    ],
    category: "rings",
    isNew: true,
    rating: 4.4,
    reviews: 39,
  },
  {
    name: "Nadia Diamond Engagement Ring",
    slug: "nadia-diamond-engagement-ring",
    tagline: "A Nadia diamond engagement ring that sparkles with brilliance", 
    description:
      " A stunning 14K yellow gold ring adorned with brilliant diamonds, perfect for adding a touch of elegance to any ensemble.",
    price: 162400,
    compareAtPrice: 164500,
    metal: "14K Yellow Gold",
    carat: 1.5,
    clarity: "VVS2",
    images: [
      '/rings/nadia-diamond-ring-2.webp',
      '/rings/nadia-diamond-ring-in-14k-yellow-gold.webp',
    ],
    category: "rings",
    isNew: true,
    rating: 4.4,
    reviews: 39,
  },
  {
    name: "Nadia Perfect Fit Diamond Ring",
    slug: "nadia-perfect-fit-diamond-ring",
    tagline: "A ring that creates a perfect fit for your finger", 
    description:
      " A stunning 18K yellow gold ring adorned with brilliant diamonds, perfect for adding a touch of elegance to any ensemble.",
    price: 162400,
    compareAtPrice: 164500,
    metal: "18K Yellow Gold",
    carat: 1.5,
    clarity: "VVS2",
    images: ['/rings/nadia-perfect-fit-diamond-ring.png', '/rings/nadia-perfect-fit-diamond-ring-2.webp'],
    category: "rings",
    isNew: true,
    rating: 4.4,
    reviews: 39,
  },
  {
    name: "Petite Twisted Vine Hidden Halo Diamond Ring",
    slug: "petite-twisted-vine-hidden-halo-diamond-ring",
    tagline: "A Halo ring that sparkles with brilliance", 
    description:
      " A stunning 14K white gold ring adorned with brilliant diamonds, perfect for adding a touch of elegance to any ensemble.",
    price: 162400,
    compareAtPrice: 164500,
    metal: "14K White Gold",
    carat: 1.5,
    clarity: "VVS2",
    images: ['/rings/petite-twisted-vine-hidden-halo.webp', '/rings/petite-twisted-vine-hidden-halo-2.webp'],
    category: "rings",
    isNew: true,
    rating: 4.4,
    reviews: 39,
  },
  {
    name: "Sydney Perfect Fit Hidden Halo Diamond Ring",
    slug: "sydney-perfect-fit-hidden-halo-diamond-ring",
    tagline: "A ring that exudes elegance and sophistication", 
    description:
      " A stunning 14K yellow gold ring adorned with brilliant diamonds, perfect for adding a touch of elegance to any ensemble.",
    price: 162400,
    compareAtPrice: 164500,
    metal: "14K Yellow Gold",
    carat: 1.5,
    clarity: "VVS2",
    images: ['/rings/sydney-perfect-fit-hidden-halo.webp', '/rings/sydney-perfect-fit-hidden-halo-2.webp'],
    category: "rings",
    isNew: true,
    rating: 4.4,
    reviews: 39,
  },
  {
    name: "Tapered Elsie Engraved Solitaire Ring",
    slug: "tapered-elsie-engraved-solitaire-ring",
    tagline: "A Solitaire ring that exudes elegance", 
    description:
      " A stunning 18K yellow gold solitaire adorned with brilliant diamonds, perfect for adding a touch of elegance to any ensemble.",
    price: 162400,
    compareAtPrice: 164500,
    metal: "18K Yellow Gold", 
    carat: 1.5, 
    clarity: "VVS2",
    images: ['/rings/tapered-elsie-engraved-solitaire-ring.png', '/rings/tapered-elsie-engraved-solitaire-ring-2.webp'], 
    category: "solitaires", 
    isNew: true,
    rating: 4.4,
    reviews: 39,
  },
  {
    name: "Sloane Flush Set Solitaire Ring",
    slug: "sloane-flush-set-solitaire-ring",
    tagline: "A single star, close to the heart",
    description:
      "A 0.6 carat lab-grown diamond suspended from a whisper-thin 18K gold chain. Minimal, luminous and endlessly versatile.",
    price: 42750,
    metal: "18K Yellow Gold",
    carat: 0.6,
    clarity: "VS1",
    images: ['/rings/sloane-flush-set-solitaire-dome-ring.png', '/rings/sloane-flush-set-solitaire-dome-ring-2.webp'],
    category: "solitaires",
    isNew: true,
    rating: 4.9,
    reviews: 37,
  },
  {
    name: "Harper Mixed Metal Solitaire Ring",
    slug: "harper-mixed-metal-solitaire-ring",
    tagline: "A solitaire that combines modernity",
    description:
      "A Harper Mixed Metal Solitaire Ring featuring a 2.0 carat VVS1 round brilliant in a timeless mixed metal setting. A solitaire that combines elegance and modernity.",
    price: 138900,
    metal: "14K Yellow Gold",
    carat: 2.0,
    clarity: "VVS1",
    images: ['/rings/harper-mixed-metal-solitaire-ring.png', '/rings/harper-mixed-metal-solitaire-ring-2.jpg'],
    category: "solitaires",
    isBestseller: true,
    rating: 5.0,
    reviews: 94,
  },
  {
    name: "Delilah Twist Solitaire Ring",
    slug: "delilah-twist-solitaire-ring",
    tagline: "A solitaire that combines elegance and modernity",
    description:
      "A Delilah Twist Solitaire Ring featuring a 2.0 carat VVS1 round brilliant in a timeless bezel prong setting. A solitaire that combines elegance and modernity.",
    price: 138900,
    metal: "14K Yellow Gold",
    carat: 2.0,
    clarity: "VVS1",
    images: ['/rings/delilah-twist-solitaire-ring.webp', '/rings/delilah-twist-solitaire-ring-2.webp'],
    category: "solitaires",
    isNew: true,
    rating: 5.0,
    reviews: 194,
  },
  {
    name: "Harper Bezel Prong Solitaire Ring",
    slug: "harper-bezel-prong-solitaire-ring",
    tagline: "The classic you'll never take off",
    description:
      "A Harper Bezel Prong Solitaire Ring featuring a 2.0 carat VVS1 round brilliant in a timeless bezel prong setting. A solitaire that combines elegance and modernity.",
    price: 138900,
    metal: "14K Yellow Gold",
    carat: 2.0,
    clarity: "VVS1",
    images: ['/rings/harper-bezel-prong-solitaire-ring.png', '/rings/harper-bezel-prong-solitaire-ring-2.webp'],
    category: "solitaires",
    isBestseller: true,
    rating: 5.0,
    reviews: 94,
  },
  {
    name: "Atelier Solitaire Ring",
    slug: "atelier-solitaire-ring",
    tagline: "A solitaire that combines elegance and modernity",
    description:
      "An Atelier Solitaire Ring featuring a 2.0 carat VS1 round brilliant in a timeless bezel prong setting.",
    price: 138900,
    compareAtPrice: 82000,
    metal: "14K Yellow Gold",
    carat: 0.8,
    clarity: "VS1",
    images: ['/rings/atelier-solitaire-ring.png', '/rings/atelier-solitaire-ring-2.jpg'],
    category: "solitaires",
    featured: true,
    rating: 4.8,
    reviews: 45,
  },
  {
    name: "Peyton Bezel Diamond Solitaire Ring",
    slug: "peyton-bezel-diamond-solitaire-ring",
    tagline: "The classic you'll never take off",
    description:
      "A Peyton Bezel Diamond Solitaire Ring featuring a 2.0 carat VVS1 round brilliant in a timeless bezel setting. A solitaire that combines elegance and modernity.",
    price: 124900,
    metal: "18K Yellow Gold",
    carat: 2.0,
    clarity: "VVS1",
    images: ['/rings/peyton-bezel-diamond-solitaire-ring.png', '/rings/peyton-bezel-diamond-solitaire-ring.jpg'],
    category: "solitaires",
    featured: true,
    isBestseller: true,
    rating: 5.0,
    reviews: 84,
  },
  {
    name: "Solitaire Ring",
    slug: "solitaire-ring",
    tagline: "A solitaire that combines  modernity",
    description:
      "A Solitaire Ring featuring a 2.0 carat VS1 round brilliant in a timeless bezel prong setting.",
    price: 138900,
    compareAtPrice: 82000,
    metal: "14K Yellow Gold",
    carat: 0.8,
    clarity: "VS1",
    images: ['/rings/atelier-solitaire-ring-3.webp', '/rings/atelier-solitaire-ring-4.jpg'],
    category: "solitaires",
    featured: true,
    rating: 4.8,
    reviews: 45,
  },
  {
    name: "Luna Diamond Pendant",
    slug: "luna-diamond-pendant",
    tagline: "A crescent of light",
    description:
      "A delicate crescent-shaped pendant in rose gold, set with a brilliant lab-grown diamond. Sweet, modern and full of light.",
    price: 56800,
    compareAtPrice: 65000,
    metal: "18K Rose Gold",
    carat: 0.5,
    clarity: "VS2",
    images: [px(27903371), px(14999288)],
    category: "pendants",
    rating: 4.7,
    reviews: 22,
  },
  {
    name: "Halo Diamond Studs",
    slug: "halo-diamond-studs",
    tagline: "The everyday essential",
    description:
      "Classic round studs with a delicate halo, set in 18K gold. The pair you reach for every morning — certified and HUID-tagged for total assurance.",
    price: 45800,
    metal: "18K Yellow Gold",
    carat: 0.4,
    clarity: "VS1",
    images: [px(5737290), px(20943478)],
    category: "earrings",
    isBestseller: true,
    rating: 4.9,
    reviews: 88,
  },
  {
    name: "Rose Drop Earrings",
    slug: "rose-drop-earrings",
    tagline: "Grace in motion",
    description:
      "Teardrop lab-grown diamonds swing gently from rose gold studs. Light, feminine and made to catch the light at every angle.",
    price: 62300,
    metal: "18K Rose Gold",
    carat: 0.7,
    clarity: "VS1",
    images: [px(35270159), px(13042449)],
    category: "earrings",
    isNew: true,
    rating: 4.8,
    reviews: 26,
  },
  {
    name: "Dahlia Diamond Hoops",
    slug: "dahlia-diamond-hoops",
    tagline: "Hoop dreams, diamond reality",
    description:
      "Chunky yet refined diamond hoops in 18K gold — 1.0 carats of continuous brilliance for the evenings that matter.",
    price: 78900,
    metal: "18K Yellow Gold",
    carat: 1.0,
    clarity: "VS2",
    images: [px(20943476), px(7981566)],
    category: "earrings",
    featured: true,
    rating: 4.8,
    reviews: 34,
  },
  {
    name: "Diamond Stud Earrings",
    slug: "diamond-stud-earrings",
    tagline: "A pair of diamond studs that sparkle with brilliance",
    description:
      "A pair of diamond stud earrings that sparkle with brilliance, perfect for adding a touch of elegance to any ensemble.",
    price: 92300,
    metal: "18K Rose Gold",
    carat: 0.7,
    clarity: "VS1",
    images: [px(35961143), px(5370644), px(8398842), px(5737290)],
    category: "earrings",
    isNew: true,
    rating: 4.8,
    reviews: 38,
  },
  {
    name: "Silver-Diamond Engagement Rings",
    slug: "silver-diamond-engagement-rings",
    tagline: "A ring that sparkles with brilliance",
    description:
      "A  multiple shaped silver-diamond rings that captures the light and attention of everyone around you.",
    price: 158900,
    metal: "Sterling Silver",
    carat: 2.0,
    clarity: "VVS1", 
    images: [px(8398837), px(8398840), px(8680199)],
    category: "rings",
    rating: 5.0,
    isBestseller: true,
    reviews: 294,
  },
  {
    name: "Pearl & Diamond Earrings",
    slug: "pearl-diamond-earrings",
    tagline: "Old-world charm, new-world ethics",
    description:
      "Freshwater pearls crowned with lab-grown diamond caps in 18K gold. A heritage silhouette with a fully sustainable soul.",
    price: 51200,
    metal: "18K Yellow Gold",
    carat: 0.3,
    clarity: "VS2",
    images: [px(29483946), px(31605846)],
    category: "earrings",
    rating: 4.7,
    reviews: 18,
  },
  {
    name: "Crown Diamond Necklace",
    slug: "crown-diamond-necklace",
    tagline: "For the queen in you",
    description:
      "A regal cascade of 2.5 carats of lab-grown diamonds in 18K gold. The Crown necklace is our most requested bridal piece.",
    price: 120500,
    compareAtPrice: 135000,
    metal: "18K Yellow Gold",
    carat: 2.5,
    clarity: "VVS1",
    images: [px(24815712), px(9322933)],
    category: "necklaces-mangalsutras",
    featured: true,
    rating: 5.0, 
    reviews: 41,
  },
  {
    name: "Diamond-encrusted Dangling Earrings",
    slug: "diamond-encrusted-dangling-earrings",
    tagline: "A pair of diamond-encrusted dangling earrings",
    description:
      "A pair of diamond-encrusted dangling earrings that sparkle with brilliance, perfect for adding a touch of elegance to any ensemble.",
    price: 86300,
    metal: "18K Rose Gold",
    carat: 0.7,  
    clarity: "VS1",
    images: [px(10983783), px(10983778), px(10983781)],
    category: "earrings",
    isNew: true,
    rating: 4.8,
    reviews: 38, 
  },
  {
    name: "Diamond Necklace & Earrings Set",
    slug: "diamond-necklace-earrings-set",
    tagline: "A perfect pair for special occasions",
    description:
      "A stunning diamond necklace and earrings set, perfect for special occasions and celebrations.",
    price: 140800,
    compareAtPrice: 155000, 
    metal: "18K Yellow Gold ",
    carat: 2.5,
    clarity: "VVS1",
    images: [px(8656236), px(7541801), px(29245549)],
    category: "necklaces-mangalsutras",
    featured: true,
    rating: 5.0,
    reviews: 41,
  },
  {
    name: "Emerald Earrings with Diamond Accents",
    slug: "emerald-earrings-diamond-accents",
    tagline: "A pair of emerald earrings with diamond accents",
    description:
      "A pair of emerald earrings with diamond accents that sparkle with brilliance, perfect for adding a touch of elegance to any ensemble.",
    price: 88300,
    metal: "18K Rose Gold",
    carat: 0.7,  
    clarity: "VS1",
    images: [px(7258925), px(17298632), px(13595821)],
    category: "earrings",
    isNew: true,
    rating: 4.8,
    reviews: 88, 
  },
  {
    name: "Aurora Diamond Necklace",
    slug: "aurora-diamond-necklace",
    tagline: "A river of light",
    description:
      "An 18-inch platinum chain carrying 1.8 carats of graduated lab-grown diamonds. Fluid, modern and utterly captivating.",
    price: 96700,
    metal: "Platinum",
    carat: 1.8,
    clarity: "VVS2",
    images: [px(14999288), px(27903371)],
    category: "necklaces-mangalsutras",
    isNew: true,
    rating: 4.9,
    reviews: 29,
  },
  {
    name: "Luxury Diamond Necklace",
    slug: "luxury-diamond-necklace",
    tagline: "A stunning diamond necklace",
    description:
      "A stunning diamond necklace that adds elegance and sophistication to any outfit.",
    price: 160800,
    compareAtPrice: 175000, 
    metal: "Platinum",
    carat: 2.5,
    clarity: "VVS1",
    images: [px(19646999), px(19647003), px(20100105)],
    category: "necklaces-mangalsutras",
    rating: 5.0,
    reviews: 51, 
  },
  {
    name: "Elegant Diamond Stud Earrings",
    slug: "elegant-diamond-stud-earrings",
    tagline: "A pair of elegant diamond stud earrings",
    description:
      "A pair of elegant diamond stud earrings that sparkle with brilliance, perfect for adding a touch of elegance to any ensemble.",
    price: 111300,
    metal: "Silver",
    carat: 0.7,  
    clarity: "VS1",
    images: [px(28389455), px(5370642), px(5442445)],
    category: "earrings",
    rating: 4.8,
    reviews: 205, 
  },
  {
    name: "Diamond Earrings With Sparkling Gemstones",
    slug: "diamond-earrings-sparkling-gemstones",
    tagline: "A pair of diamond earrings with sparkling gemstones",
    description:
      "A pair of diamond earrings  with sparkling gemstones that sparkle with brilliance, perfect for adding a touch of elegance to any ensemble.",
    price: 111300,
    metal: "Silver", 
    carat: 0.7,  
    clarity: "VS1",
    images: [px(15684102), px(11836371), px(9900047)],
    category: "earrings",
    rating: 4.8,
    reviews: 255, 
  },
  {
    name: "Rose Gold and Diamond Pendant",
    slug: "rose-gold-diamond-pendant",
    tagline: "A stunning rose gold and diamond pendant",
    description:
      "A stunning rose gold and diamond pendant that adds elegance and sophistication to any outfit.",
    price: 190800,
    compareAtPrice: 185000,  
    metal: "Rose Gold",
    carat: 2.5,
    clarity: "VVS1", 
    images: [px(8306527), px(18157531), px(7541807)],
    category: "pendants",
    isNew: true,
    rating: 5.0,
    reviews: 121,
  },
  {
    name: "Diamond Pendant",
    slug: "diamond-pendant",
    tagline: "A stunning diamond pendant",
    description:
      "A stunning diamond pendant that adds elegance and sophistication to any outfit.",
    price: 180800,
    compareAtPrice: 175000, 
    metal: "Rose Gold",
    carat: 2.5,
    clarity: "VVS1", 
    images: [px(10983785), px(10983782), px(10983785)],
    category: "pendants",
    featured: true,
    rating: 5.0,
    reviews: 81,
  },
  {
    name: "Luxurious Diamond Necklace & Earrings Set", 
    slug: "luxurious-diamond-necklace-and-earrings",
    tagline: "A stunning diamond necklace and earrings set",
    description:
      "A stunning diamond necklace and earrings set that adds elegance and sophistication to any outfit.",
    price: 180800, 
    compareAtPrice: 175000, 
    metal: "Rose Gold",
    carat: 2.5,
    clarity: "VVS1",
    images: [px(7541803), px(16082501), px(7541805)],
    category: "necklaces-mangalsutras",
    featured: true, 
    rating: 5.0,
    reviews: 190,
  },
  {
    name: "Tennis Diamond Bracelet",
    slug: "tennis-diamond-bracelet",
    tagline: "The icon, reimagined",
    description:
      "A continuous line of 2.2 carats of lab-grown diamonds in 18K gold. The tennis bracelet that belongs on every wrist.",
    price: 88900,
    metal: "18K Yellow Gold",
    carat: 2.2,
    clarity: "VS1",
    images: [px(38827895), px(38827914)],
    category: "bangles-bracelets",
    isBestseller: true,
    rating: 4.9,
    reviews: 73,
  },
  {
    name: "Diamond Mangalsutra",
    slug: "diamond-mangalsutra",
    tagline: "A diamond mangalsutra that exudes elegance & sophistication",
    description:
      " A diamond mangalsutra that exudes elegance and sophistication, perfect for special occasions and celebrations.",
    price: 120800,
    compareAtPrice: 145000, 
    metal: "18K Yellow Gold",
    carat: 2.5,
    clarity: "VVS1",
    images: [px(8306531), px(34511063), px(15827870)],
    category: "necklaces-mangalsutras",
    rating: 5.0,
    reviews: 251,
  },
  {
    name: "Regal Gold Bangle",
    slug: "regal-gold-bangle",
    tagline: "Tradition, polished to perfection",
    description:
      "A substantial 22K gold bangle with diamond accents — heirloom craftsmanship reimagined for modern wrists.",
    price: 96400,
    compareAtPrice: 112000,
    metal: "22K Yellow Gold",
    carat: 1.0,
    clarity: "VS2",
    images: [px(32874211), px(34399150)],
    category: "bangles-bracelets",
    featured: true,
    rating: 4.8,
    reviews: 38,
  },
  {
    name: "Bridal Diamond Bangle",
    slug: "bridal-diamond-bangle",
    tagline: "For the biggest days",
    description:
      "An intricate 22K gold bangle studded with 1.4 carats of diamonds, made to shine from the mehndi to the pheras.",
    price: 108300,
    metal: "22K Yellow Gold",
    carat: 1.4,
    clarity: "VS1",
    images: [px(14873626), px(20626511)],
    category: "bangles-bracelets",
    rating: 4.9,
    reviews: 27,
  },
  {
    name: "Diamond Encrusted Bracelets",
    slug: "diamond-encrusted-bracelets",
    tagline: "A pair of diamond encrusted bracelets that sparkle with brilliance",
    description:
      "A pair of diamond encrusted bracelets that sparkle with brilliance, perfect for adding a touch of elegance to any ensemble.",
    price: 108300,
    metal: "22K Rose Gold",
    carat: 1.4,
    clarity: "VS1",
    images: [px(6716442), px(29245553), px(29245553)],
    category: "bangles-bracelets",
    rating: 4.9,
    reviews: 127,
  },
  {
    name: "Silver Bracelet with Diamond Charm",
    slug: "silver-bracelet-with-diamond-charm",
    tagline: "A pair of diamond encrusted bracelets that sparkle with brilliance",
    description:
      "A pair of diamond encrusted bracelets that sparkle with brilliance, perfect for adding a touch of elegance to any ensemble.",
    price: 108300,
    metal: "Sterling Silver",
    carat: 1.4,
    clarity: "VS1",
    images: [px(14509677), px(29245553), px(12194308)],
    category: "bangles-bracelets",
    rating: 4.9,
    reviews: 227,
  },
  
];

async function main() {
  console.log("Clearing existing data…");
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.product.deleteMany();
  await prisma.category.deleteMany();

  console.log("Seeding categories…");
  for (const c of categories) {
    await prisma.category.create({ data: c });
  }

  console.log("Seeding products…");
  for (const p of products) {
    const { category, ...data } = p;
    await prisma.product.create({
      data: {
        ...data,
        category: {
          connect: { slug: category },
        },
      },
    });
  }

  const counts = await Promise.all([
    prisma.category.count(),
    prisma.product.count(),
  ]);
  console.log(`Done! ${counts[0]} categories, ${counts[1]} products.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
